---
- name: create a mongodb container
  docker_container:
    name: mongodb
    image: mongo:4.0.10-xenial
    network_mode: host
    restart_policy: unless-stopped
    volumes:
      - /data/mongodb/data:/data/db
